# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "update"
  update:
    # The type of runner that the job will run on
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        runner: [ test-farm1, test-farm2 ] # Replace with your runner names

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: ssh-agent-submodule-fix
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.TEST_TMP }}

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
              cd ~/Documents/github_test/_work/test/test
              git pull
              git submodule update --init --recursive
              node index.js
